export const USER_INFO = "USER_INFO";
export const TOKEN = "EL_TOKEN";
export const MY_COURSE_ALL = "MY_COURSE_ALL";
export const MY_COURSE_WAIT_ACCEPT = "MY_COURSE_WAITING_ACCEPT";
export const MY_COURSE_NOT_JOIN = "MY_COURSE_NOT_JOIN";
export const MY_COURSE_WAS_JOIN = "MY_COURSE_WAS_JOIN";